# course_mappings.py

course_skills = {
    'Direito': ['Argumentação', 'Direito Civil', 'Legislação'],
    'Administração Pública': ['Gestão Pública', 'Políticas Públicas', 'Orçamento Público'],
    'Engenharia Civil': ['CAD', 'Gestão de Obras', 'Estruturas'],
    'Medicina': ['Diagnóstico Clínico', 'Atendimento de Emergência', 'Patologia'],
    'Física': ['Mecânica Quântica', 'Eletromagnetismo', 'Termodinâmica'],
    'Medicina Veterinária': ['Clínica Veterinária', 'Cirurgia Veterinária', 'Bem-estar Animal'],
    'Agronomia': ['Manejo do Solo', 'Agricultura Sustentável', 'Fitotecnia'],
    'Engenharia Mecânica': ['Termodinâmica', 'Mecânica dos Fluidos', 'Desenho Técnico'],
    'Matemática': ['Álgebra', 'Cálculo', 'Estatística'],
    'Engenharia Física': ['Óptica', 'Mecânica Aplicada', 'Física Moderna'],
    'Filosofia': ['Lógica', 'Ética', 'Metafísica'],
    'Ciências Biológicas': ['Biologia Molecular', 'Ecologia', 'Genética'],
    'Nutrição': ['Dietética', 'Nutrição Clínica', 'Segurança Alimentar'],
    'Química': ['Química Orgânica', 'Bioquímica', 'Análise Química'],
    'Engenharia de Materiais': ['Ciência dos Materiais', 'Propriedades Mecânicas', 'Metalurgia'],
    'Letras': ['Gramática', 'Literatura', 'Linguística'],
    'Ciência da Computação': ['Programação', 'Estrutura de Dados', 'Algoritmos'],
    'Administração': ['Gestão Financeira', 'Marketing', 'Recursos Humanos'],
    'ABI Letras': ['Crítica Literária', 'Análise Textual', 'Produção Textual'],
    'Bacharelado Interdisciplinar em Inovação, Ciência e Tecnologia (BICT)': ['Pensamento Inovador', 'Gestão de Projetos', 'Empreendedorismo'],
    'Letras/Português': ['Análise Literária', 'Redação Avançada', 'Literatura Brasileira'],
    'Letras Português, Inglês e suas Literaturas': ['Tradução', 'Ensino de Idiomas', 'Literatura Comparada'],
    'Pedagogia': ['Didática', 'Psicologia Educacional', 'Gestão Escolar'],
    'ABI Engenharia': ['Gestão de Projetos', 'Análise Técnica', 'Inovação Tecnológica'],
    'Engenharia Agrícola': ['Máquinas Agrícolas', 'Hidráulica Agrícola', 'Gestão Agrícola'],
    'Engenharia Florestal': ['Manejo Florestal', 'Conservação da Natureza', 'Silvicultura'],
    'Engenharia de Controle e Automação': ['Sistemas de Controle', 'Robótica', 'Automação Industrial'],
    'Zootecnia': ['Genética Animal', 'Nutrição Animal', 'Produção Animal'],
    'ABI Educação Física': ['Treinamento Desportivo', 'Anatomia do Movimento', 'Nutrição Esportiva'],
    'Engenharia Química': ['Processos Químicos', 'Termodinâmica Química', 'Operações Unitárias'],
    'Engenharia de Alimentos': ['Bioquímica de Alimentos', 'Microbiologia de Alimentos', 'Processamento de Alimentos'],
    'Sistemas de Informação': ['Banco de Dados', 'Redes de Computadores', 'Segurança da Informação'],
    'Educação Física': ['Treinamento Esportivo', 'Anatomia Humana', 'Nutrição Esportiva'],
    'Engenharia Ambiental e Sanitária': ['Gestão de Resíduos', 'Avaliação de Impacto Ambiental', 'Legislação Ambiental'],
    'Letras/Inglês': ['Linguística Aplicada', 'Tradução', 'Ensino de Inglês como Segunda Língua'],
    'Administração Piloto EAD': ['Gestão de Projetos', 'Marketing Digital', 'Administração Financeira']}


course_interests = {
    'Direito': ['Prática Jurídica', 'Direitos Humanos', 'Compliance'],
    'Administração Pública': ['Gestão Pública', 'Políticas Públicas', 'Orçamento e Finanças Públicas'],
    'Engenharia Civil': ['Projetos de Infraestrutura', 'Gestão de Construções', 'Engenharia Urbana'],
    'Medicina': ['Saúde Pública', 'Cirurgia Geral', 'Medicina Interna'],
    'Física': ['Pesquisa Científica', 'Educação em Física', 'Física Aplicada'],
    'Medicina Veterinária': ['Clínica Veterinária', 'Saúde Animal', 'Bem-estar Animal'],
    'Agronomia': ['Agricultura Sustentável', 'Gestão Agropecuária', 'Biotecnologia Agrícola'],
    'Engenharia Mecânica': ['Desenvolvimento de Produtos', 'Sistemas Mecânicos', 'Engenharia Térmica'],
    'Matemática': ['Educação Matemática', 'Pesquisa Operacional', 'Matemática Aplicada'],
    'Engenharia Física': ['Desenvolvimento de Materiais', 'Instrumentação Científica', 'Nanotecnologia'],
    'Filosofia': ['Ética Aplicada', 'Lógica', 'História da Filosofia'],
    'Ciências Biológicas': ['Biodiversidade', 'Biologia Molecular', 'Ecologia'],
    'Nutrição': ['Saúde e Alimentação', 'Nutrição Clínica', 'Segurança Alimentar'],
    'Química': ['Química Analítica', 'Química Ambiental', 'Bioquímica'],
    'Engenharia de Materiais': ['Nanomateriais', 'Ciência dos Polímeros', 'Metalurgia'],
    'Letras': ['Literatura', 'Linguística', 'Ensino de Línguas'],
    'Ciência da Computação': ['Desenvolvimento de Software', 'Inteligência Artificial', 'Ciência de Dados'],
    'Administração': ['Gestão Empresarial', 'Marketing', 'Finanças Corporativas'],
    'ABI Letras': ['Crítica Literária', 'Análise Textual', 'Produção de Conteúdo'],
    'Bacharelado Interdisciplinar em Inovação, Ciência e Tecnologia (BICT)': ['Inovação Tecnológica', 'Empreendedorismo em Tecnologia', 'Gestão da Inovação'],
    'Letras/Português': ['Gramática Normativa', 'Literatura Brasileira', 'Produção Textual'],
    'Letras Português, Inglês e suas Literaturas': ['Estudos Literários', 'Tradução', 'Ensino Bilingue'],
    'Pedagogia': ['Educação Infantil', 'Gestão Educacional', 'Educação Inclusiva'],
    'ABI Engenharia': ['Gestão de Projetos de Engenharia', 'Inovação em Engenharia', 'Engenharia Sustentável'],
    'Engenharia Agrícola': ['Mecanização Agrícola', 'Hidráulica Agrícola', 'Gestão de Recursos Hídricos'],
    'Engenharia Florestal': ['Manejo Florestal', 'Conservação de Ecossistemas', 'Silvicultura'],
    'Engenharia de Controle e Automação': ['Robótica', 'Sistemas de Controle', 'Automação Industrial'],
    'Zootecnia': ['Produção Animal', 'Genética Animal', 'Nutrição Animal'],
    'ABI Educação Física': ['Esportes Coletivos', 'Treinamento Físico', 'Recreação e Lazer'],
    'Engenharia Química': ['Processos Químicos', 'Engenharia de Processos', 'Tecnologia de Alimentos'],
    'Engenharia de Alimentos': ['Qualidade e Segurança Alimentar', 'Processamento de Alimentos', 'Desenvolvimento de Novos Produtos'],
    'Sistemas de Informação': ['Gerenciamento de Sistemas de Informação', 'Segurança da Informação', 'Análise de Sistemas'],
    'Educação Física': ['Preparação Física', 'Fisiologia do Exercício', 'Gestão Esportiva'],
    'Engenharia Ambiental e Sanitária': ['Sustentabilidade', 'Consultoria Ambiental', 'Engenharia Hídrica'],
    'Letras/Inglês': ['Literatura Inglesa', 'Correção de Textos', 'Intercâmbio Cultural'],
    'Administração Piloto EAD': ['Empreendedorismo', 'E-commerce', 'Gestão de Startups']}